extends:
  ./node_modules/readable-code/.eslintrc.yml

rules:
  css-modules/no-unused-class: off

overrides:
  files:
    - "**.test.js"

  rules:
    no-empty-function: off
    lodash/prefer-noop: off
    react/jsx-no-bind: off
